apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-forwarded
  namespace: eshop
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: eshop
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: eshop-https-forwarded@kubernetescrd
spec:
  rules:
    - host: eshop.marmaracse.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 8080
    - host: identity.eshop.marmaracse.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-api
                port:
                  number: 8080
    - host: webhook.eshop.marmaracse.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-client
                port:
                  number: 8080
