apiVersion: v1
kind: Secret
metadata:
  name: eshop-secrets
  namespace: eshop
type: Opaque
stringData:
  # --- Database connection strings ---
  catalogdb-connection: "Host=db;Database=catalogdb;Username=root;Password=pass"
  identitydb-connection: "Host=db;Database=identitydb;Username=root;Password=pass"
  orderingdb-connection: "Host=db;Database=orderingdb;Username=root;Password=pass"
  webhooksdb-connection: "Host=db;Database=webhooksdb;Username=root;Password=pass"
  # --- Redis ---
  redis-connection: "cache,password=pass"
  # --- RabbitMQ ---
  eventbus-connection: "amqp://root:pass@queue:5672"