apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-processor-config
  namespace: eshop
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.eshop.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_SERVICE_NAME: "payment-processor"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  namespace: eshop
  labels:
    app: payment-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      imagePullSecrets:
        - name: nexus-registry
      containers:
        - name: payment-processor
          image: 192.168.1.175:8082/eshop/payment-processor:v2
          envFrom:
            - configMapRef:
                name: payment-processor-config
          env:
            - name: ConnectionStrings__EventBus
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eventbus-connection
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
